<Workspace Version="0.9.0.3067" X="-1409.51888602455" Y="-418.071844722409" zoom="0.766680702705775" Name="Atmos.XY.pointsDistribution" Description="Creates a points distribution based off divisions across the XY Plane from a selection of Revit Model lines" ID="c0ee5c07-2df1-477d-a326-caf0f4ce101e" Category="Atmos.XYPlaneNodes">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="9f50b3b5-5d21-43dd-9978-b933cef79828" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="93.2133333333334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="modelLines" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="a15dd3aa-4415-44d2-8d08-18c2a01f9d23" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="494.294335838562" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="resolution: int = 20" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="4076d7eb-eff8-4240-93b4-b22e06a7595e" type="Dynamo.Nodes.Output" nickname="Output" x="2697.17969820802" y="967.958144913661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="groupedPointList" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="2033d968-171b-4215-b6f6-1000e460509a" type="Dynamo.Nodes.Output" nickname="Output" x="2697.17969820802" y="883.958144913661" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="singlePointList" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="3b44ffed-cd72-453d-b537-c603ce1232f0" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="304.90846277938" y="-290.209942817847" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="t2 = t3.Curves;&#xA;t4 = t2.ToNurbsCurve();&#xA;t5 = t4.EndPoint;&#xA;t6 = Flatten(t5);&#xA;t7 = t4.StartPoint;&#xA;t8 = Flatten(t7);&#xA;t9 = t4.ControlPoints();&#xA;t10 = Flatten(t9);&#xA;t11 = {t6, t8, t10};&#xA;t12 = Flatten(t11);&#xA;t13 = Point.PruneDuplicates(t12, 0.001);&#xA;t14 = t13.X;&#xA;t15 = List.MaximumItem(t14);&#xA;t16 = t13.Y;&#xA;t17 = List.MinimumItem(t16);&#xA;t18 = Point.ByCoordinates(t15, t17, 0);&#xA;t19 = List.MinimumItem(t14);&#xA;t20 = Point.ByCoordinates(t19, t17, 0);&#xA;t21 = List.MaximumItem(t16);&#xA;t22 = Point.ByCoordinates(t19, t21, 0);&#xA;t23 = Point.ByCoordinates(t15, t21, 0);&#xA;t24 = {t18, t20, t22, t23};&#xA;t25 = Rectangle.ByCornerPoints(t24);&#xA;t26 = t25.Curves();&#xA;t27 = t26.PointAtParameter(0.5);&#xA;t28 = t26.EndPoint;&#xA;t29 = Line.ByStartPointEndPoint(t18, t22);&#xA;t30 = Line.ByStartPointEndPoint(t23, t20);&#xA;t31 = t29.Intersect(t30);" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="2ce16ca6-3f71-46d9-aa0d-0edc708a2ac2" type="Dynamo.Nodes.DSFunction" nickname="Element.Curves" x="296.7858236908" y="323.903629030653" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="RevitNodes.dll" function="Revit.Elements.Element.Curves" />
    <Dynamo.Nodes.DSFunction guid="ecb49093-2d8e-4ed2-8d0c-ee0109740646" type="Dynamo.Nodes.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="554.7858236908" y="375.491654531683" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="14a83713-ab98-46a0-a2ea-7aaf870656aa" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="554.7858236908" y="483.851654531683" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="0..1..#divs;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="862.91378287529" y="296.486809022633" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="//Input elements&#xA;bec=BaseElementCurves;&#xA;frame=rectangle.Curves();&#xA;divs=Divisons;&#xA;clT = ClashThickness;&#xA;//Conversions&#xA;bec0=PolyCurve.ByJoinedCurves(bec);&#xA;surface0=Surface.ByPatch(bec0);&#xA;surface1 = surface0.Thicken(clT,true);&#xA;//Picking off the Sub-Elements&#xA;side0=frame[0];&#xA;side1=frame[1];&#xA;side2=frame[2];&#xA;side3=frame[3];&#xA;//Points at Parameter&#xA;p0=side0.PointAtParameter(divs);&#xA;p1=side1.PointAtParameter(divs);&#xA;p2=side2.PointAtParameter(divs);&#xA;p3=side3.PointAtParameter(divs);&#xA;//Reversing the alternate lists&#xA;rp1=List.Reverse(p2);&#xA;rp3=List.Reverse(p3);&#xA;//Creating lines from said points lists&#xA;line0=Line.ByStartPointEndPoint(p0,rp1);&#xA;line1=Line.ByStartPointEndPoint(p1,rp3);&#xA;//Cleaning up the lists&#xA;cline0 = List.Clean(line0,false);&#xA;cline1 = List.Clean(line1,false);&#xA;//Doing an intersect&#xA;srfintersect0=Flatten(cline0.Intersect(surface1));&#xA;lineintersect0=Flatten(srfintersect0.Intersect(cline1&lt;1&gt;&lt;2&gt;));" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="81c8102c-c64d-47eb-aef1-99f4d8b65edb" type="Dynamo.Nodes.DSFunction" nickname="Point.X" x="1954.43657285443" y="1219.96879833059" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="cea6381c-82ff-45e6-8f07-b960c6837e08" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1943.99464435003" y="929.556539011943" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="precision = 0.01;&#xA;&#xA;px = inp.X;&#xA;py = inp.Y;&#xA;pz = inp.Z;&#xA;&#xA;ppx = Math.Round(px/precision)*precision;&#xA;ppy = Math.Round(py/precision)*precision;&#xA;ppz = Math.Round(pz/precision)*precision;&#xA;&#xA;pp = Point.ByCoordinates(ppx,ppy,ppz);" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="12296c19-4926-435b-ac13-74742ebd44f8" type="Dynamo.Nodes.DSFunction" nickname="Point.X" x="1954.43657285443" y="1329.54213166391" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X" />
    <Dynamo.Nodes.DSFunction guid="f17a7a3e-3748-4390-ada0-1856c53063b1" type="Dynamo.Nodes.DSFunction" nickname="SortByFunction" x="2418.8595046425" y="1169.92072727041" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="SortByFunction@var[]..[],_FunctionObject" />
    <Dynamo.Nodes.DSFunction guid="d9031d27-67ef-476e-be7f-afac36a2d364" type="Dynamo.Nodes.DSFunction" nickname="GroupByFunction" x="2577.45246033522" y="1270.61466739277" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="GroupByFunction@var[]..[],_FunctionObject" />
    <Dynamo.Nodes.Symbol guid="a7d85579-7595-424a-bbec-27af4a8d903b" type="Dynamo.Nodes.Symbol" nickname="Input" x="-2.7376283901508" y="571.167916668377" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="clashThickness: int = 2500" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="13ac2cf5-e5bb-4366-8087-3a1e7c17c47d" type="Dynamo.Nodes.Output" nickname="Output" x="2697.49499832496" y="1050.39712417901" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="centroid" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="9f50b3b5-5d21-43dd-9978-b933cef79828" start_index="0" end="3b44ffed-cd72-453d-b537-c603ce1232f0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9f50b3b5-5d21-43dd-9978-b933cef79828" start_index="0" end="2ce16ca6-3f71-46d9-aa0d-0edc708a2ac2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a15dd3aa-4415-44d2-8d08-18c2a01f9d23" start_index="0" end="14a83713-ab98-46a0-a2ea-7aaf870656aa" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3b44ffed-cd72-453d-b537-c603ce1232f0" start_index="22" end="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="3b44ffed-cd72-453d-b537-c603ce1232f0" start_index="28" end="13ac2cf5-e5bb-4366-8087-3a1e7c17c47d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2ce16ca6-3f71-46d9-aa0d-0edc708a2ac2" start_index="0" end="ecb49093-2d8e-4ed2-8d0c-ee0109740646" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ecb49093-2d8e-4ed2-8d0c-ee0109740646" start_index="0" end="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="14a83713-ab98-46a0-a2ea-7aaf870656aa" start_index="0" end="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" start_index="22" end="cea6381c-82ff-45e6-8f07-b960c6837e08" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="81c8102c-c64d-47eb-aef1-99f4d8b65edb" start_index="0" end="f17a7a3e-3748-4390-ada0-1856c53063b1" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="cea6381c-82ff-45e6-8f07-b960c6837e08" start_index="7" end="f17a7a3e-3748-4390-ada0-1856c53063b1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="cea6381c-82ff-45e6-8f07-b960c6837e08" start_index="7" end="2033d968-171b-4215-b6f6-1000e460509a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="12296c19-4926-435b-ac13-74742ebd44f8" start_index="0" end="d9031d27-67ef-476e-be7f-afac36a2d364" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="f17a7a3e-3748-4390-ada0-1856c53063b1" start_index="0" end="d9031d27-67ef-476e-be7f-afac36a2d364" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d9031d27-67ef-476e-be7f-afac36a2d364" start_index="0" end="4076d7eb-eff8-4240-93b4-b22e06a7595e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a7d85579-7595-424a-bbec-27af4a8d903b" start_index="0" end="34b9990f-c810-4bdd-9dc8-f5840fa8fd01" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-21946.4760259717" eyeY="21059.2673563202" eyeZ="62309.1663817108" lookX="25946.258313648" lookY="-32090.9730695677" lookZ="-44599.1673902946" upX="0.167857976343584" upY="0.942641491092185" upZ="-0.288532006975576" />
  </Cameras>
</Workspace>