<Workspace Version="0.9.0.3067" X="165.729088190878" Y="102.611055335895" zoom="1.04258072467361" Name="Atmos.XY.frameExtents" Description="Gathers the maximum and minimum points from a selection of model lines to create an extent frame. Output gives you the frame rectangle, corner points, centre points of frame and centroid of shape. " ID="e2b1fec9-f497-4bb5-ad4d-94f208d98d29" Category="Atmos.XYPlaneNodes">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="8d16da34-8b3f-432d-9732-5f912e0c0dd7" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="modelCurves" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="35f2ab68-fc8c-462f-8b79-207e303f65b2" type="Dynamo.Nodes.Output" nickname="Output" x="734" y="388.546666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="centrePoints" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="1f0c232c-4c00-456d-b944-020ea663a2df" type="Dynamo.Nodes.Output" nickname="Output" x="734" y="472.546666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="cornerPoints" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="e291f40a-938e-488b-91a6-6597c2fc103f" type="Dynamo.Nodes.Output" nickname="Output" x="734" y="555.546666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="centroid" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="85f334aa-bdc3-4b41-9cb6-d2d7beec466a" type="Dynamo.Nodes.Output" nickname="Output" x="734" y="305.546666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="rectangle" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="The Guts" x="225" y="4.21333333333331" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="t2 = t3.Curves;&#xA;t4 = t2.ToNurbsCurve();&#xA;t5 = t4.EndPoint;&#xA;t6 = Flatten(t5);&#xA;t7 = t4.StartPoint;&#xA;t8 = Flatten(t7);&#xA;t9 = t4.ControlPoints();&#xA;t10 = Flatten(t9);&#xA;t11 = {t6, t8, t10};&#xA;t12 = Flatten(t11);&#xA;t13 = Point.PruneDuplicates(t12, 0.001);&#xA;t14 = t13.X;&#xA;t15 = List.MaximumItem(t14);&#xA;t16 = t13.Y;&#xA;t17 = List.MinimumItem(t16);&#xA;t18 = Point.ByCoordinates(t15, t17, 0);&#xA;t19 = List.MinimumItem(t14);&#xA;t20 = Point.ByCoordinates(t19, t17, 0);&#xA;t21 = List.MaximumItem(t16);&#xA;t22 = Point.ByCoordinates(t19, t21, 0);&#xA;t23 = Point.ByCoordinates(t15, t21, 0);&#xA;t24 = {t18, t20, t22, t23};&#xA;t25 = Rectangle.ByCornerPoints(t24);&#xA;t26 = t25.Curves();&#xA;t27 = t26.PointAtParameter(0.5);&#xA;t28 = t26.EndPoint;&#xA;t29 = Line.ByStartPointEndPoint(t18, t22);&#xA;t30 = Line.ByStartPointEndPoint(t23, t20);&#xA;t31 = t29.Intersect(t30);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8d16da34-8b3f-432d-9732-5f912e0c0dd7" start_index="0" end="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" start_index="22" end="85f334aa-bdc3-4b41-9cb6-d2d7beec466a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" start_index="24" end="35f2ab68-fc8c-462f-8b79-207e303f65b2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" start_index="25" end="1f0c232c-4c00-456d-b944-020ea663a2df" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5c36a9d0-de2d-4a0d-ba17-5a48957951b7" start_index="28" end="e291f40a-938e-488b-91a6-6597c2fc103f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-21946.4760259717" eyeY="21059.2673563202" eyeZ="62309.1663817108" lookX="25946.258313648" lookY="-32090.9730695677" lookZ="-44599.1673902946" upX="0.167857976343584" upY="0.942641491092185" upZ="-0.288532006975576" />
  </Cameras>
</Workspace>