{
  "Uuid": "0490c879-ad31-4845-aaa0-3efd67e04022",
  "IsCustomNode": true,
  "Category": "GeniusLoci.Level",
  "Description": "Gets an element's level.\r\nBased on a Clockwork's node",
  "Name": "Element Level",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "element",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "0e342b4e3a7b4ea4ad7efeaaa676fcc6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "37eae418a2894729b378383e1afeff9b",
          "Name": "",
          "Description": "Symbole",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Un paramètre de fonction, utiliser avec des noeuds personnalisés.\r\n\r\nVous pouvez spécifier le type et la valeur par défaut du paramètre. Par exemple,\r\n\r\nentrée: var[]..[]\r\nvaleur: bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "level",
      "Id": "1d3a5181d0f34eeb96472ee00c94e33d",
      "Inputs": [
        {
          "Id": "ca469faa4dd44404b48b43e32afefba3",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Sortie de fonction, utiliser avec les noeuds personnalisés"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\n#Definition by Daniel Woodcock\r\ndef getSketchIds(item):\r\n\teIds = []\r\n\tt = Transaction(item.Document, \"Temp\")\r\n\tt.Start()   \r\n\teIds = item.Document.Delete(item.Id) \r\n\tt.RollBack()  \r\n\treturn eIds\r\n\t\r\n#Inspired by Clockwork\r\ndef GetLevel(item):\r\n\tval = None\r\n\tdoc = item.Document\r\n\tif item.Category != None and item.Category.CategoryType != CategoryType.Internal :\r\n\t\tif item.Category.Id == ElementId(BuiltInCategory.OST_Rebar) :\r\n\t\t\titem = doc.GetElement(item.GetHostId())\r\n\t\tif (item.GetType().ToString() in (\"Autodesk.Revit.DB.Architecture.StairsRun\", \"Autodesk.Revit.DB.Architecture.StairsLanding\")):\r\n\t\t\titem = item.GetStairs()\r\n\t\tif hasattr(item, \"LevelId\"): \r\n\t\t\tval = doc.GetElement(item.LevelId)\r\n\t\tif hasattr(item, \"Level\"):\r\n\t\t\tval = item.Level\r\n\t\tif hasattr(item, \"GenLevel\"):\r\n\t\t\tval = item.GenLevel\r\n\t\tif (item.GetType().ToString() == \"Autodesk.Revit.DB.Architecture.Stairs\") or item.Category.Id == ElementId(BuiltInCategory.OST_Ramps):\r\n\t\t\ttry: val = doc.GetElement(item.get_Parameter(BuiltInParameter.STAIRS_BASE_LEVEL_PARAM).AsElementId())\r\n\t\t\texcept: pass\r\n\t\tif (item.GetType().ToString() == \"Autodesk.Revit.DB.ExtrusionRoof\"):\r\n\t\t\ttry: val = doc.GetElement(item.get_Parameter(BuiltInParameter.ROOF_CONSTRAINT_LEVEL_PARAM).AsElementId())\r\n\t\t\texcept: pass\r\n\t\t#if (item.GetType().ToString() == \"Autodesk.Revit.DB.Mechanical.Duct\" or item.GetType().ToString() == \"Autodesk.Revit.DB.Electrical.Conduit\"):\r\n\t\t\t#try: return doc.GetElement(item.get_Parameter(BuiltInParameter.RBS_START_LEVEL_PARAM).AsElementId())\r\n\t\t\t#except: pass\r\n\t\tif hasattr(item, \"OwnerViewId\"):\r\n\t\t\tview = doc.GetElement(item.OwnerViewId)\r\n\t\t\tif hasattr(view, \"GenLevel\"):\r\n\t\t\t\tval = view.GenLevel\r\n\t\tif not val:\r\n\t\t\tcollector = FilteredElementCollector(doc).OfClass(Level).ToElements()\r\n\t\t\t\r\n\t\t\tif isinstance(item,FamilyInstance) and item.Symbol.Family.IsInPlace:\r\n\t\t\t\tids = getSketchIds(item)\r\n\t\t\t\telems = [doc.GetElement(id) for id in ids]\r\n\t\t\t\tlName = next((ex.get_Parameter(BuiltInParameter.SKETCH_PLANE_PARAM).AsString() for ex in elems if ex.GetType() == Extrusion), None)\r\n\t\t\t\ttry: val = [level for level in collector if lName.split(\": \")[-1] == level.Name][0]\r\n\t\t\t\texcept: pass\r\n\t\t\telse:\r\n\t\t\t\ttry: val = doc.GetElement(item.get_Parameter(BuiltInParameter.INSTANCE_REFERENCE_LEVEL_PARAM).AsElementId())\r\n\t\t\t\texcept: \r\n\t\t\t\t\ttry: val = doc.GetElement(item.get_Parameter(BuiltInParameter.INSTANCE_SCHEDULE_ONLY_LEVEL_PARAM).AsElementId())\r\n\t\t\t\t\texcept: \r\n\t\t\t\t\t\ttry: val = doc.GetElement(item.get_Parameter(BuiltInParameter.SCHEDULE_LEVEL_PARAM).AsElementId())\r\n\t\t\t\t\t\texcept:\r\n\t\t\t\t\t\t\t#if item is work plane based\r\n\t\t\t\t\t\t\ttry: val = [level for level in collector if item.get_Parameter(BuiltInParameter.SKETCH_PLANE_PARAM).AsString().split(\": \")[-1] == level.Name][0]\r\n\t\t\t\t\t\t\texcept : val\r\n\treturn val\r\n\t\r\nProcessLists = lambda function, lists: [ProcessLists(function, item) if isinstance(item, list) else function(item) for item in lists]\r\nApplyFunction = lambda func, objs: ProcessLists(func, objs) if isinstance(objs, list) else [func(objs)]\r\n\r\ndef Unwrap(item):\r\n    return UnwrapElement(item)\r\n    \r\nif isinstance(IN[0], list):\r\n\titems = ProcessLists(Unwrap, IN[0])\r\nelse:\r\n\titems = Unwrap(IN[0])\r\n\r\nOUT=ApplyFunction(GetLevel,items)",
      "Engine": "IronPython2",
      "EngineName": "IronPython2",
      "VariableInputPorts": true,
      "Id": "43a834e5ede14b05bedb2470d7ae1dbd",
      "Inputs": [
        {
          "Id": "b2221aba323f4e9bb09d45ad54588f5b",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7ffeeaf015514e989b7b72a42851e031",
          "Name": "OUT",
          "Description": "Résultat du script Python",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Exécute un script Python intégré."
    }
  ],
  "Connectors": [
    {
      "Start": "37eae418a2894729b378383e1afeff9b",
      "End": "b2221aba323f4e9bb09d45ad54588f5b",
      "Id": "db90a35ad10b4da089269e26289d53d6",
      "IsHidden": "False"
    },
    {
      "Start": "7ffeeaf015514e989b7b72a42851e031",
      "End": "ca469faa4dd44404b48b43e32afefba3",
      "Id": "8384496586be4c3bb450554475cfc44c",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.2.5624",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Aperçu en arrière-plan",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Input",
        "ShowGeometry": true,
        "Id": "0e342b4e3a7b4ea4ad7efeaaa676fcc6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 166.55275569915474,
        "Y": 256.5030035226053
      },
      {
        "Name": "Output",
        "ShowGeometry": true,
        "Id": "1d3a5181d0f34eeb96472ee00c94e33d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 686.68155491065181,
        "Y": 262.57339225026828
      },
      {
        "Name": "Python Script",
        "ShowGeometry": true,
        "Id": "43a834e5ede14b05bedb2470d7ae1dbd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 453.85103938700377,
        "Y": 261.33532111617075
      }
    ],
    "Annotations": [],
    "X": 271.001609941079,
    "Y": 107.88044888635109,
    "Zoom": 0.52486542792448554
  }
}